name: 'spotify_downloader'
description: App with which you can download tracks from Spotify using YouTube
publish_to: 'none'
repository: 'https://github.com/C0ntrolDev/spotify_downloader'

version: 1.1.2+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  oauth2_client: ^3.2.2
  http: ^1.1.0
  spotify: ^0.12.0
  path_provider: ^2.1.1
  get_it: ^7.6.4
  sqflite: ^2.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  auto_route: ^7.8.4
  palette_generator: ^0.3.3+3
  ffmpeg_kit_flutter_full: ^6.0.3
  youtube_explode_dart: ^2.3.6
  metadata_god: ^0.5.2
  cached_network_image: ^3.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  modal_bottom_sheet: ^3.0.0
  awesome_notifications_core: ^0.8.1
  awesome_notifications: ^0.8.2
  file_picker: ^6.1.1
  device_info_plus: ^10.1.1
  permission_handler: ^11.1.0
  intl: ^0.19.0
  flutter_localizations:
        sdk: flutter
  dropdown_button2: ^2.3.9
  flutter_background: ^1.3.0+1
  async: ^2.11.0
  sliver_tools: ^0.2.12
  scrollbar_ultima: ^1.0.3
  package_info_plus: ^8.0.1
  url_launcher: ^6.3.0
  flutter_oss_licenses: ^3.0.2
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

dependency_overrides:
  win32: ^5.5.4

flutter:

  uses-material-design: true

  assets:
    - resources/images/svg/bottom_bar/history_icon_active.svg
    - resources/images/svg/bottom_bar/history_icon.svg
    - resources/images/svg/bottom_bar/home_icon_active.svg
    - resources/images/svg/bottom_bar/home_icon.svg
    - resources/images/svg/track_tile/cancel_icon.svg
    - resources/images/svg/track_tile/reload_icon.svg
    - resources/images/svg/track_tile/download_icon.svg
    - resources/images/svg/track_tile/error_icon.svg
    - resources/images/svg/track_tile/downloaded_icon.svg
    - resources/images/svg/track_tile/more_info.svg
    - resources/images/svg/download_track_info/reference_icon.svg
    - resources/images/svg/download_track_info/edit_icon.svg
    - resources/images/svg/settings_icon.svg
    - resources/images/svg/search_icon.svg
    - resources/images/svg/back_icon.svg
    - resources/images/another/loading_track_collection_image.png
    - resources/images/another/bestIcon3.png
    - resources/images/another/thanks.png



  fonts:
    - family: OpenSans
      fonts:
        - asset: resources/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: resources/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: resources/fonts/OpenSans-ExtraBold.ttf
          weight: 800
flutter_intl: 
  enabled: true
