name: spotify_downloader
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  oauth2_client: ^2.4.2
  http: ^0.13.6
  spotify: ^0.11.0
  path_provider: ^2.1.1
  get_it: ^7.6.4
  sqflite: ^2.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.5
  auto_route: ^7.8.4
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/images/svg/settings_icon.svg
    - resources/images/svg/search_icon.svg
    - resources/images/svg/back_icon.svg
    - resources/images/another/liked_tracks.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: resources/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: resources/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: resources/fonts/OpenSans-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
